name: Frappe Docker Build and Deploye Arc-POS

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy"
        required: true
        default: "arc-pos"
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          repository: Excel-Technologies-Ltd/excel-frappe-docker

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitLab Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.GITLAB_USERNAME }}
          password: ${{ secrets.GITLAB_PASSWORD }}

      - name: Build and Push Frappe Docker Image
        run: |
          # Define apps JSON
          export APPS_JSON='[
            {
              "url": "https://github.com/frappe/erpnext",
              "branch": "version-14"
            },
            {
              "url": "https://github.com/frappe/hrms.git",
              "branch": "version-14"
            },
            {
              "url": "https://github.com/Excel-Technologies-Ltd/excel_restaurant_pos.git",
              "branch": "arc-pos"
            },
            {
              "url": "https://github.com/Excel-Technologies-Ltd/Excel-ERPNext.git",
              "branch": "arc-pos"
            },
            {
              "url": "https://github.com/Excel-Technologies-Ltd/uber-direct.git",
              "branch": "main"
            }
          ]'

          # Convert apps JSON to base64
          export APPS_JSON_BASE64=$(echo ${APPS_JSON} | base64 -w 0)

          # Define all tags
          DOCKER_HUB_TAG="arcapps/arc-pos:latest"
          GITLAB_TAG="registry.gitlab.com/arcapps/arc-container-registry/arc-pos:latest"
          
          # Build once with multiple tags and push to all registries
          docker buildx build \
            --no-cache \
            --platform linux/amd64 \
            --build-arg FRAPPE_PATH=https://github.com/frappe/frappe \
            --build-arg FRAPPE_BRANCH=version-14 \
            --build-arg PYTHON_VERSION=3.11.9 \
            --build-arg NODE_VERSION=20.19.2 \
            --build-arg APPS_JSON_BASE64="$APPS_JSON_BASE64" \
            --tag "$DOCKER_HUB_TAG" \
            --tag "$GITLAB_TAG" \
            --file images/custom/Containerfile \
            --push .
